plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/jaiparmani/Desktop/SELF/TECH/DEVELOPMENT/ToolBoxProject/ToolBoxFrontend/toolbox-frontend/build"
publishOrigin = "config"
commandOrigin = "config"
base = "/Users/jaiparmani/Desktop/SELF/TECH/DEVELOPMENT/ToolBoxProject/ToolBoxFrontend/toolbox-frontend"
command = "npm run build"

[build.environment]
CI = "false"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]